version: "3.4"

services:
  webserver.api:
    container_name: webserver-api
    build:
      context: "."
      dockerfile: WebServer/Dockerfile
      args:
        config: Debug
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTPS_PORT: 443
      POSTGRES_CONNSTR: Host=postgres;Port=5432;Database=db;User ID=dbuser;Password=dbpass;Pooling=true;
      DB_CONTAINER_NAME: postgres
      START_URL: http://0.0.0.0:443
    image: api
    depends_on:
      - postgres
    restart: always
    volumes:
      - "./logs:/logs"
    ports:
      - "8072:80"
      - "8073:443"
    networks:
      - net
  postgres:
    container_name: postgres
    build:
      context: "."
      dockerfile: postgres/Dockerfile
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data
    image: postgres:10.0
    ports:
      - "54320:5432"
    networks:
      - net
networks:
  net:
    driver: bridge
